[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["backend/tests"]

[tool.coverage.run]
source = ["backend"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.mypy]
python_version = "3.10"
warn_unused_ignores = true
warn_redundant_casts = true
strict = true
