from typing import Any

class Config:
    def __init__(self, file_: Any = ...) -> None: ...
    def set_main_option(self, name: Any, value: Any) -> None: ...

def main(argv: Any = ...) -> Any: ...
def file_config(argv: Any = ...) -> Any: ...
