from typing import Any

class Config:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_main_option(self, name: Any, value: Any) -> Any: ...

def main(argv: Any = ...) -> Any: ...
def file_config(argv: Any = ...) -> Any: ...
