name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  read-roadmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rappel lecture docs/roadmap.md
        run: |
          echo "Relire docs/ROADMAP.md et aligner le code; proposer patch si divergence."
  backend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Backend deps
        run: |
          python -m pip install -U pip
          python -m venv backend/.venv
          backend/.venv/Scripts/pip install -r backend/requirements.txt
      - name: Lints
        run: |
          backend/.venv/Scripts/python -m ruff check backend
          backend/.venv/Scripts/python -m mypy backend
      - name: Tests
        run: |
          backend/.venv/Scripts/python -m pytest -q --disable-warnings --maxfail=1
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Frontend lint
        run: |
          cd frontend
          npm ci
          npm run lint
  docs-guard:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Docs guard
        shell: pwsh
        run: |
          ./tools/docs_guard.ps1
          ./tools/readme_check.ps1
