name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  read-roadmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rappel lecture docs/roadmap.md
        run: |
          echo "Relire docs/ROADMAP.md et aligner le code; proposer patch si divergence."
  backend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Backend deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          python -m venv backend/.venv
          backend\.venv\Scripts\pip install -r backend\requirements.txt
          if (Test-Path "backend\requirements-dev.txt") { backend\.venv\Scripts\pip install -r backend\requirements-dev.txt }
      - name: Lints
        shell: pwsh
        run: |
          backend\.venv\Scripts\python -m ruff check backend
          backend\.venv\Scripts\python -m mypy --config-file backend\mypy.ini backend
      - name: Tests
        shell: pwsh
        env:
          PYTHONPATH: backend
        run: |
          backend\.venv\Scripts\python -m pytest -q --disable-warnings --maxfail=1
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Force npm registry public (CI)
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "always-auth=false" >> .npmrc
          echo "fund=false" >> .npmrc
          echo "audit=false" >> .npmrc
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Frontend lint
        run: |
          cd frontend
          npm ci --no-audit --no-fund --registry=https://registry.npmjs.org/
          npm run lint
  docs-guard:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Docs guard
        shell: pwsh
        run: |
          ./tools/docs_guard.ps1
          ./tools/readme_check.ps1
