name: e2e-conflits
on:
  pull_request:
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/e2e-conflits.yml"
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Install FE
        working-directory: frontend
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install BE
        working-directory: backend
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install -r requirements.txt || true
      - name: Launch BE
        working-directory: backend
        run: |
          nohup python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 2
      - name: Launch FE
        working-directory: frontend
        env:
          VITE_API_BASE: "http://127.0.0.1:8000"
        run: |
          nohup npm run dev -- --host 0.0.0.0 --port 5173 &
          sleep 3
      - name: e2e Playwright
        working-directory: frontend
        env:
          PLAYWRIGHT_BASE_URL: "http://127.0.0.1:5173"
        run: npx playwright test tests/e2e/conflicts.spec.ts --reporter=dot
