name: frontend-storybook
on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-storybook.yml"
jobs:
  storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 + npm cache (frontend lockfile)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install deps (frontend)
        run: npm ci --no-audit --no-fund

      - name: Lint (ts/eslint)
        run: |
          if (npm run -q lint 2>$null) { exit 0 } else { echo "lint script absent, skip"; exit 0; }

      - name: Build storybook
        run: npm run build-storybook -- --quiet

      - name: Smoke serve + probe (6006)
        run: |
          npx --yes http-server storybook-static -p 6006 >/dev/null 2>&1 &
          for i in {1..30}; do
            curl -sf http://127.0.0.1:6006/ && exit 0
            sleep 1
          done
          echo "storybook not ready"; exit 3

      - name: Bundle budget (size-limit)
        run: |
          if (npm run -q size 2>$null) { npm run size; } else { echo "size-limit absent, skip"; }
