name: storybook
on:
  pull_request:
    paths:
      - "frontend/**"
      - "**/*.stories.*"
      - ".github/workflows/storybook.yml"
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - "**/*.stories.*"
      - ".github/workflows/storybook.yml"

jobs:
  storybook:
    name: storybook
    runs-on: ubuntu-latest
    # Phase 1 non bloquante: meme en cas d'echec, le job ne casse pas la CI
    continue-on-error: true
    env:
      # Node memory headroom si build local est utilise
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install deps (frontend)
        working-directory: frontend
        run: |
          npm ci

      # OPTION A (recommandee): Chromatic (build distant, stable)
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
          exitZeroOnChanges: true
          onlyChanged: true
          autoAcceptChanges: true
          zip: true
        # Si secret absent (forks), eviter l'echec dur: step soft-fail
        continue-on-error: true

      # OPTION B (backup local) si Chromatic indisponible: build local pour detecter les erreurs de compilation
      - name: Build Storybook locally (backup)
        working-directory: frontend
        run: |
          npx storybook build --ci
        continue-on-error: true
