name: storybook
on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/storybook.yml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: storybook-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build-storybook
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Build Storybook
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npx storybook build
      - name: Upload static storybook
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: frontend/storybook-static
          retention-days: 2

  storybook-tests:
    name: storybook-tests
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Download storybook artifact
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: frontend/storybook-static
      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium
      - name: Run Storybook tests (a11y smoke)
        run: |
          npx http-server storybook-static -p 6006 &
          sleep 3
          npx test-storybook --url http://127.0.0.1:6006 --maxWorkers=2

  chromatic:
    name: publish-chromatic
    needs: build
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Skip (token absent)
        if: ${{ env.CHROMATIC_PROJECT_TOKEN == '' || env.CHROMATIC_PROJECT_TOKEN == null }}
        run: echo "CHROMATIC_PROJECT_TOKEN absent. Publication Chromatic ignoree."
      - name: Publish to Chromatic
        if: ${{ env.CHROMATIC_PROJECT_TOKEN != '' && env.CHROMATIC_PROJECT_TOKEN != null }}
        run: |
          npx chromatic --project-token "$CHROMATIC_PROJECT_TOKEN" --ci --only-changed --exit-zero-on-changes --auto-accept-changes
        continue-on-error: true
